apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
spec:
  replicas: 30
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
        - name: ingestor
          image: marcobevilacqua94/ingestor:latest
          command: ["java","-jar","app.jar","-h","cb-example-persistent"]